# Generated by Django 3.0.7 on 2020-06-13 01:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('daka', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=32, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('daka_time', models.DateTimeField(null=True, verbose_name='最后一次打卡时间')),
            ],
        ),
        migrations.RemoveField(
            model_name='log',
            name='user',
        ),
        migrations.AddField(
            model_name='log',
            name='created',
            field=models.DateTimeField(auto_now=True, verbose_name='创建时间'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='log',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daka.Task', verbose_name='对应任务'),
            preserve_default=False,
        ),
    ]
