# Generated by Django 3.0.7 on 2020-06-13 10:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('daka', '0002_auto_20200613_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='提醒邮箱'),
        ),
        migrations.AlterField(
            model_name='task',
            name='daka_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后一次打卡时间'),
        ),
    ]
