# Generated by Django 3.0.2 on 2020-06-13 15:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('daka', '0003_auto_20200613_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='email',
        ),
    ]
