# Generated by Django 3.0.2 on 2020-06-13 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('daka', '0004_remove_task_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='注册时间'),
        ),
    ]
